version: 0.2

phases:
  install:
    commands:
      - npm install --only=production
  test:
    commands:
      - npm run test
  build:
    commands:
      - npm run build-prod

artifacts:
  secondary-artifacts:
    artifact1:
      base-directory: $CODEBUILD_SRC_DIR
      files:
        - source1_file
    artifact2:
      base-directory: $CODEBUILD_SRC_DIR_source2
      files:
        - source2_file