version: 0.2

phases:
  pre_install:
    commands:
      - echo Updating Cloudformation Stack
      - aws cloudformation update-stack --stack-name Cull-UI-Stack --template-body file://./cloudformation.template.yml --capabilities CAPABILITY_IAM
  install:
    commands:
      - echo Installing dependencies
      - npm install
  test:
    commands:
      - echo Running unit tests
      - npm run test
  build:
    commands:
      - echo Building production application
      - npm run build-prod
  post_build:
    commands:
      - echo Build completed

cache:
  paths:
    - 'node_modules/**/*'

# Where the build artifacts are located -- is this necessary for the pipeline?
artifacts:
  files:
    - '**/*'
  base-directory: dist