interface IUserConstants
{
    REGISTER_REQUEST: string,
    REGISTER_SUCCESS: string,
    REGISTER_ERROR: string,

    LOGIN_REQUEST: string,
    LOGIN_SUCCESS: string,
    LOGIN_FAILURE: string,

    LOGOUT_REQUEST: string,
    LOGOUT_SUCCESS: string,
    LOGOUT_FAILURE: string,

    AUTH_REQUEST: string,
    AUTH_SUCCESS: string,
    AUTH_FAILURE: string
};

export const userConstants: IUserConstants =
{
    REGISTER_REQUEST: 'REGISTER_REQUEST',
    REGISTER_SUCCESS: 'REGISTER_SUCCESS',
    REGISTER_ERROR: 'REGISTER_ERROR',

    LOGIN_REQUEST: 'LOGIN_REQUEST',
    LOGIN_SUCCESS: 'LOGIN_SUCCESS',
    LOGIN_FAILURE: 'LOGIN_FAILURE',

    LOGOUT_REQUEST: 'LOGOUT_REQUEST',
    LOGOUT_SUCCESS: 'LOGOUT_SUCCESS',
    LOGOUT_FAILURE: 'LOGOUT_FAILURE',

    AUTH_REQUEST: 'AUTH_REQUEST',
    AUTH_SUCCESS: 'AUTH_SUCCESS',
    AUTH_FAILURE: 'AUTH_FAILURE'
};